apiVersion: v1
kind: Pod
metadata: 
  name: web
  labels:
    name: web
    app: chomeshvan-node
spec:
  containers:
    - image: supersid/chomeshvan
      name: chomeshvan
      env:
        - name: REDIS_URL
          value: redis://10.111.67.3:6379
      ports: 
        - containerPort: 8000
  imagePullSecrets:
    - name: myregistrykey