apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    name: web
    app: chomeshvan-node-service
spec:
  selector:
    name: web
  type: NodePort
  ports:
  - name: http
    port: 80
    nodePort: 30001
    targetPort: 8000
    protocol: TCP
