apiVersion: v1
kind: ReplicationController
metadata:
  name: web
  labels:
    name: web
    app: chomeshvan-node
spec:
  replicas: 2
  selector:
    name: web
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
        - name: chomeshvan-node
          image: supersid/chomeshvan
          env:
          - name: REDIS_URL
            # value: redis://10.111.67.3:6379
            value: redis://redis-service:6379
          ports: 
            - containerPort: 8000
      imagePullSecrets:
        - name: myregistrykey
          
