apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    name: redis
    app: chomeshvan-redis-service
spec:
  selector:
    name: redis
  type: ClusterIP   
  ports:
  - name: redis
    port: 6379
    targetPort: 6379 #pod container port
